export default {
  firstTime: true,
  worker: false,
  imgsWorker: false,
  socket: false,
  loading: require('../assets/loading.jpg'),
  isConnected: false,
  shippingCost: 35,
  taxFee: 7,
  star: [],
  bag: [],
  ordered: [],
  buyerInfo: { name: '', address: '', phone: '', email: '', pass: '' },
  homeItemInfo: [],
  mess: [],
  prods: [],
  list: { _id: '', _rev: '', value: [] },
}
