export default {
  firstTime: true,
  worker: false,
  imgWorker: false,
  socket: false,
  loading: require('../assets/loading.jpg'),
  shippingCost: 35,
  taxFee: 7,
  star: [],
  bag: [],
  ordered: [],
  buyerInfo: { name: '', address: '', phone: '', email: '', pass: '' },
  homeItemInfo: [],
  sliderData: null,
  buyerId: '',
  mess: [],
  prods: [],
  list: { _id: '', _rev: '', value: [] },
  url: 'https://res.cloudinary.com/dgprt0eay/image/upload/',
}
